---
 - name: Install Qemu/KVM
   yum:
    pkg:
    - libvirt
    - qemu
    - qemu-kvm
   when: (ansible_distribution_major_version == "7")

 - name: Install Qemu/KVM
   dnf:
    pkg:
    - libvirt
    - qemu
    - qemu-kvm
   when: (ansible_distribution_major_version == "8")