---
- hosts: server
  become: yes
  vars:
    gns3_url: http://localhost
    clients: "true"
    docker: "true"
    ubuntu: "false"
    kali: "false"

  roles:
       - basic
       - kvm
       - gns3-server
       - reboot

- import_playbook: clients.yml
  when: clients == "true"
  