---
- hosts: server
  become: yes
  vars:
    gns3_url: http://localhost
    clients: "true"
    docker: "true"
# Docker image
    ubuntu_img: "false"
    kali_img: "false"
# GNS3 Client    
    srv_on_client: "true"

  roles:
       - basic
       - kvm
       - gns3-server
       - reboot

- import_playbook: clients.yml
  when: clients == "true"
  