---
- hosts: servers
  become: yes
  vars:
    gns3_url: http://localhost
    docker: "True"
    kali_img: "False"

  roles:
       - common
       - kvm
       - role: gns3server_build
         when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
       - gns3-server
       - reboot

  tasks:
    - set_fact:
        ansible_python_interpreter: /usr/bin/python3 #Set python3 at task level for centos7
    - name: Get the server facts
      gns3_module:
        url: "{{ gns3_url }}"
        port: 3080
        page: "version"
      register: gns3_version

    - debug: var=gns3_version