---
 - name: Install needed tools
   apt:
     pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

 - name: Add Docker GPG apt Key
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

 - name: Add Docker Repository
   apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

 - name: Update apt and install docker-ce
   apt:
     name: docker-ce
     update_cache: yes

 - name: Add GNS3 user to docker group
   user:
     name: gns3
     groups: ubridge, libvirt, kvm, docker
     append: yes

 - name: Docker python SDK
   pip:
    name: docker 

 - name: Enable docker daemon
   systemd:
     name: docker
     state: started
     enabled: yes

 - include: gns3-docker-img.yml