--- 
 - name: pull kalilinux image
   docker_image:
     name: gns3/kalilinux
     source: pull
   when: kali == 'yes'

 - name: pull Ubuntu image
   docker_image:
     name: gns3/ubuntu
     source: pull
   when: ubuntu == 'yes'