---
 - name: Create GNS3 group
   group: 
    name: gns3
    state: present

 - name: Create GNS3 users
   user:
    name: gns3
    group: gns3
    groups:  libvirt, kvm
    comment: gns3 user

 - include: gns3-docker-centos.yml
   when: docker == "True"  and (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

 - name: GNS3-server
   pip:
    name: gns3-server==2.2.5
    executable: pip3

 - name: Systemd file
   copy:
      src: "{{ role_path }}/files/lib/systemd/system/gns3_centos.service"
      dest: /lib/systemd/system/gns3.service

 - name: Enable gns3
   systemd:
    name: gns3
    enabled: yes

 - name: Open Firewalld 3080 port for GNS3
   firewalld:
    port: 3080/tcp
    permanent: yes
    state: enabled
    zone: public