---
 - name: Setup EPEL repo
   become: yes
   yum:
       name: epel-release
   when: ansible_distribution_major_version == "7"

 - name: Install tools and dep
   become: yes
   yum:
     name: "{{ packages }}"
   vars:
     packages:
          - gcc
          - python3-devel
          - python3-pip
          - python36-psutil
          - python36-pyqt4-sip
          - python36-pyqt5-sip
          - python36-qt5
          - python36-qt5-devel
          - wireshark-gnome
          - xterm
   when: ansible_distribution_major_version == "7"

 - name: Setup EPEL repo
   become: yes
   dnf:
       name: epel-release
   when: ansible_distribution_major_version == "8"

 - name: Install tools and dep
   become: yes
   dnf:
     name: "{{ packages }}"
   vars:
     packages:
          - gcc
          - python3-devel
          - python3-pip
          - python3-psutil
          - python3-pyqt5-sip
          - python3-qt5
          - wireshark
          - xterm
   when: ansible_distribution_major_version == "8"

 - name: Install PyPiP
   become: yes
   dnf:
       name: python3-pip
   when: ansible_distribution_major_version == "8"

 - name: GNS3-Gui
   pip:
    name: gns3-gui==2.2.5
    executable: pip3

 - name: GNS3-server
   pip:
    name: gns3-server==2.2.5
    executable: pip3