---
 - name: Install tools and dep
   dnf:
     name: "{{ packages }}"
   vars:
     packages:
          - python3-devel
          - python3-pip
          - python3-psutil
          - python3-pyqt5-sip
          - python3-qt5
          - wireshark-gnome

 - name: Install PyPiP
   dnf:
       name: python3-pip

 - name: GNS3-Gui
   pip:
    name: gns3-gui==2.2.5
    executable: pip3

 - name: GNS3-server
   pip:
    name: gns3-server==2.2.5
    executable: pip3
   when: srv_on_client == "true"