---
 - include: ubuntu.yml
   when: ansible_distribution == "Ubuntu"

 - include: centos.yml
   when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

 - include: fedora.yml
   when: ansible_distribution == "Fedora"