---
 - name: Add ppa
   apt_repository:
      repo: ppa:gns3/ppa
      
 - name: Install GNS3 gui and wireshark
   apt:
    update_cache: yes
    pkg:
    - gns3-gui
    - wireshark-gtk

 - name: Install gns3 server on client
   apt:
    update_cache: yes
    pkg:
    - gns3-server
   when: srv_on_client == "True"